before_script:
  - echo "before script"
  # let users can modify its own files.
  # git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/

after_script:
  - echo "after script"

stages:
  - test_run


eGADA:
  stage: test_run
  script:
    - echo "Compiling eGADA and test its C++ binary ... "
    - pwd
    - cd src && make
    - ./eGADA -i ../data/input.txt -o ./output_CPP.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - src/output_CPP.tsv

pyGADA:
  stage: test_run
  script:
    - echo "Compiling eGADA and test-run its Python module ... "
    - pwd
    - cd src && make
    - ./testGADA.py -i ../data/input.txt -o ./output_py.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - src/output_py.tsv

docker_pyGADA:
  stage: test_run
  script:
    - echo "Run the program inside the docker... "
    - pwd
    - docker pull docker.yfish.x/egada:latest
    - docker run -v `pwd`:/abc -t docker.yfish.x/egada:latest /opt/eGADA/testGADA.py -i /abc/data/input.txt -o /abc/data/output_docker_py.tsv
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 3 mos
    paths:
    - ./data/output_docker_py.tsv
